# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-27 08:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('month', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=512)),
                ('image', models.ImageField(upload_to='')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendar_moe.Date')),
            ],
        ),
    ]
