# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-27 10:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_moe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=512)),
                ('image', models.ImageField(upload_to='uploads/dates/')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendar_moe.Date')),
            ],
        ),
        migrations.RemoveField(
            model_name='image',
            name='date',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
